# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/anarchy.gpte.redhat.com_anarchycommunes.yaml
# Copied by Makefile from ../helm/crds
- bases/anarchyactions.yaml
- bases/anarchygovernors.yaml
- bases/anarchyrunners.yaml
- bases/anarchyruns.yaml
- bases/anarchysubjects.yaml
# Copied by Makefile from ../kopfpeerings.crd.yaml
- bases/kopfpeerings.crd.yaml
#+kubebuilder:scaffold:crdkustomizeresource
