# Based on https://github.com/zalando-incubator/kopf/blob/master/peering.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kopfpeerings.zalando.org
spec:
  group: zalando.org
  names:
    kind: KopfPeering
    plural: kopfpeerings
    singular: kopfpeering
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        status:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object
  version: v1
