---
- name: GitOps Setup
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    anarchy_gitops_deploy_autonomous: true
    set_k8s_cluster_info: {}
    k8s_config:
      run_interval: 1h
    k8s_config_sources:
    - name: anarchy-k8s-config
      base_path: "{{ playbook_dir }}/k8s-config"
      
  pre_tasks:
  - name: Get OpenShift API server information
    k8s_info:
      api_version: config.openshift.io/v1
      kind: ClusterOperator
      name: openshift-apiserver
    register: _k8s_info_cluster_operator_openshift_apiserver

  - name: Get cluster ingress configuration
    k8s_info:
      api_version: config.openshift.io/v1
      kind: Ingress
      name: cluster
    register: _k8s_info_get_cluster_ingress

  - name: Set k8s_cluster_info with set_k8s_cluster_info and discovered information
    set_fact:
      k8s_cluster_info: >-
        {{ set_k8s_cluster_info | combine({
        "cluster_domain":
          _k8s_info_get_cluster_ingress.resources[0].spec.domain | regex_replace('^apps\\.', ''),
        "cluster_ingress_domain":
          _k8s_info_get_cluster_ingress.resources[0].spec.domain,
        }) }}

  - name: Set openshift_api_version and openshift_api_minor_version
    set_fact:
      openshift_api_minor_version: >-
        {{ _k8s_info_cluster_operator_openshift_apiserver.resources[0]
         | json_query("status.versions[?name=='openshift-apiserver']|[0].version")
         | regex_replace("\.\d+$", "")
        }}
      openshift_api_version: >-
        {{ _k8s_info_cluster_operator_openshift_apiserver.resources[0]
         | json_query("status.versions[?name=='openshift-apiserver']|[0].version")
        }}

  roles:
  - role: k8s_config
