apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyGovernor
metadata:
  name: gitops
spec:
  runner: default
  ansibleGalaxyRequirements:
    collections: []
    roles:
    - name: k8s_config
      src: git+{{ .Values.k8s_config.repo }}
      version: {{ .Values.k8s_config.version }}
  vars:
    k8s_config:
      {{- toYaml .Values.k8s_config | nindent 6 }}
    k8s_cluster_info:
      {{- toYaml .Values.k8s_cluster_info | nindent 6 }}
  subjectEventHandlers:
    create:
      tasks:
      - name: Schedule Deploy
        anarchy_schedule_action:
          action: configure
    update:
      tasks:
      - name: Schedule Deploy
        anarchy_schedule_action:
          action: configure
  actions:
    configure:
      pre_tasks:
      - name: Get OpenShift API server information
        k8s_info:
          api_version: config.openshift.io/v1
          kind: ClusterOperator
          name: openshift-apiserver
        register: _k8s_info_cluster_operator_openshift_apiserver

      - name: Set openshift_api_version and openshift_api_minor_version
        set_fact:
          openshift_api_minor_version: >-
            {{ _k8s_info_cluster_operator_openshift_apiserver.resources[0]
             | json_query("status.versions[?name=='openshift-apiserver']|[0].version")
             | regex_replace("\.\d+$", "")
            }}
          openshift_api_version: >-
            {{ _k8s_info_cluster_operator_openshift_apiserver.resources[0]
             | json_query("status.versions[?name=='openshift-apiserver']|[0].version")
            }}

      roles:
      - k8s_config

      tasks:
      - name: Schedule next run
        anarchy_schedule_action:
          action: configure
          after: {{ .Values.k8s_config.run_interval }}
